services:
  appointmentservice:
    image: appointmentservice
    build:
      context: .
      dockerfile: AppointmentService/Dockerfile

  PetService:
    image: pet-service
    build:
      context: .
      dockerfile: PetService/Dockerfile

  TreatmentAndNotificationService:
    image: treatment-and-notification-service
    build:
      context: .
      dockerfile: TreatmentAndNotificationService/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    
  TreatmentAndNotificationDatabase:
    image: postgres:16-alpine
    container_name: treatment_pg_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: treatments_db
    ports:
      - "5553:5432"
    volumes:
      - treatment_data:/var/lib/postgresql/data

volumes:
  treatment_data:
