@PetCarePlatform.AppointmentService.Api_HostAddress = http://localhost:5138

GET {{PetCarePlatform.AppointmentService.Api_HostAddress}}/health
Accept: application/json

###

GET {{PetCarePlatform.AppointmentService.Api_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

# Swagger UI (open in browser, not usable from the .http runner):
# {{PetCarePlatform.AppointmentService.Api_HostAddress}}/swagger
