import { ReactNode, useEffect, useMemo, useState } from 'react';
import { ApiError, createApi, type PetCareApi } from './api';
import { accountSettingsUrl, completeLogin, getSession, logout, redirectToLogin } from './auth';
import type { Appointment, Clinic, Examination, Notification, Owner, Pet, Session, Slot, Vaccination, Veterinarian } from './types';

type Page = 'overview' | 'directory' | 'appointments' | 'care' | 'notifications' | 'profile';
const role = (session: Session, ...allowed: string[]) => allowed.some(item => session.roles.includes(item));
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const date = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`)) : '—';
const inputDateTime = (value = new Date()) => new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
const today = () => new Date().toISOString().slice(0, 10);
const list = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean);
const petSpecies: Record<string, number> = { Dog: 1, Cat: 2, Bird: 3, Rabbit: 4, Reptile: 5, Other: 99 };
const appointmentStatus = (value: string | number) => ({ 1: 'Scheduled', 2: 'Completed', 3: 'Cancelled' }[Number(value)] ?? String(value));
const notificationStatus = (value: string | number) => ({ 1: 'Pending', 2: 'Sent', 3: 'Failed' }[Number(value)] ?? String(value));

function errorMessage(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong. Please try again.'; }

function App() {
  const [session, setSession] = useState<Session | null>(getSession());
  const [authError, setAuthError] = useState<string | null>(null);
  const [settling, setSettling] = useState(true);
  useEffect(() => {
    completeLogin().then(setSession).catch(error => setAuthError(errorMessage(error))).finally(() => setSettling(false));
  }, []);
  if (settling) return <div className="auth-screen"><div className="paw" aria-hidden="true">🐾</div><p>Preparing your PetCare workspace…</p></div>;
  if (!session) return <Login error={authError} />;
  return <Workspace session={session} onExpired={() => { sessionStorage.clear(); setSession(null); }} />;
}

function Login({ error }: { error: string | null }) {
  return <main className="auth-screen">
    <div className="login-card">
      <div className="login-brand"><span className="brand-mark" aria-hidden="true">🐾</span><span>PetCare</span></div>
      <h1>One place for every pet’s care.</h1>
      <p className="muted">Sign in securely through Keycloak to manage pet profiles, schedules, treatment records, vaccinations, and service notifications.</p>
      {error && <p className="alert error">{error}</p>}
      <button className="primary full" onClick={() => void redirectToLogin()}>Continue with Keycloak <span>→</span></button>
      <p className="hint">Use your organization account to continue securely.</p>
    </div>
  </main>;
}

function Workspace({ session, onExpired }: { session: Session; onExpired: () => void }) {
  const api = useMemo(() => createApi(session.accessToken), [session.accessToken]);
  const [page, setPage] = useState<Page>('overview');
  const [owners, setOwners] = useState<Owner[]>([]);
  const [pets, setPets] = useState<Pet[]>([]);
  const [selectedOwner, setSelectedOwner] = useState('');
  const [selectedPet, setSelectedPet] = useState('');
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<string | null>(null);
  const ownerOnly = role(session, 'owner') && !role(session, 'admin');
  const admin = role(session, 'admin');
  const canUseDirectory = role(session, 'owner', 'admin');
  const loadDirectory = async () => {
    if (!canUseDirectory) { setOwners([]); setPets([]); setSelectedOwner(''); setSelectedPet(''); setLoading(false); return; }
    try {
      const [nextOwners, nextPets] = await Promise.all([api.owners(), api.pets()]);
      const visibleOwners = ownerOnly ? nextOwners.filter(owner => owner.ownerId === session.subject) : nextOwners;
      const visiblePets = ownerOnly ? nextPets.filter(pet => pet.ownerId === session.subject) : nextPets;
      setOwners(visibleOwners); setPets(visiblePets);
      setSelectedOwner(current => visibleOwners.some(owner => owner.ownerId === current) ? current : visibleOwners[0]?.ownerId ?? '');
      setSelectedPet(current => visiblePets.some(pet => pet.petId === current) ? current : visiblePets[0]?.petId ?? '');
    } catch (error) { if (error instanceof ApiError && error.status === 401) onExpired(); else setNotice(errorMessage(error)); }
    finally { setLoading(false); }
  };
  useEffect(() => { void loadDirectory(); }, [api]);
  const owner = owners.find(item => item.ownerId === selectedOwner);
  const pet = pets.find(item => item.petId === selectedPet);
  const viewProps = { api, session, owners, pets, selectedOwner, setSelectedOwner, selectedPet, setSelectedPet, refreshDirectory: loadDirectory, inform: setNotice };
  const navigation = ([['overview', 'Overview'], ['directory', admin ? 'Clients' : 'My pets'], ['appointments', 'Appointments'], ['care', 'Clinical care'], ['notifications', 'Notifications']] as [Page, string][]).filter(([id]) => canUseDirectory || id !== 'directory');
  const signedInOwner = owners.find(item => item.ownerId === session.subject);
  const accountName = signedInOwner?.ownerName ?? (session.username === 'vet1' ? 'Dr. Alex Morgan' : session.username);
  return <div className="app-shell">
    <aside className="sidebar"><div className="logo"><span aria-hidden="true">🐾</span><div>PetCare</div></div>
      <nav>{navigation.map(([id, label]) => <button key={id} className={page === id ? 'nav active' : 'nav'} onClick={() => setPage(id)}>{label}</button>)}</nav>
      <div className="sidebar-footer"><button className={page === 'profile' ? 'account-button active' : 'account-button'} onClick={() => setPage('profile')} aria-label="Open your profile"><span className="avatar">{accountName.slice(0, 1).toUpperCase()}</span><span className="account-copy"><b>{accountName}</b><small>{session.roles.filter(item => ['owner', 'veterinarian', 'admin'].includes(item)).join(' · ') || 'authenticated'}</small></span></button><button aria-label="Sign out" className="icon-button logout-button" onClick={logout}><span aria-hidden="true">↪</span><span>Logout</span></button></div>
    </aside>
    <main className="content"><header className="topbar"><div><p className="eyebrow">{page.replace('-', ' ')}</p><h2>{page === 'overview' ? 'Good to see the whole picture.' : page === 'directory' ? admin ? 'Manage clients and veterinarians' : 'Everything about your pets' : page === 'appointments' ? 'Coordinate care with confidence' : page === 'care' ? 'A complete clinical timeline' : page === 'profile' ? 'Manage your profile' : 'Keep everyone informed'}</h2></div>{canUseDirectory && page !== 'profile' && <ContextPicker owners={owners} pets={pets} ownerId={selectedOwner} petId={selectedPet} setOwner={setSelectedOwner} setPet={setSelectedPet} lockOwner={ownerOnly} />}</header>
      {notice && <div className="toast"><span>{notice}</span><button onClick={() => setNotice(null)}>×</button></div>}
      {loading ? <div className="loading">Loading platform data…</div> : <>
        {page === 'overview' && (canUseDirectory ? <Overview {...viewProps} /> : <VeterinarianOverview api={api} session={session} inform={setNotice} />)}
        {page === 'directory' && canUseDirectory && <Directory {...viewProps} />}
        {page === 'appointments' && <AppointmentsPage {...viewProps} />}
        {page === 'care' && <CarePage {...viewProps} />}
        {page === 'notifications' && <NotificationsPage {...viewProps} />}
        {page === 'profile' && <ProfilePage api={api} session={session} owners={owners} refreshDirectory={loadDirectory} inform={setNotice} />}
      </>}
      {canUseDirectory && !owner && !pet && owners.length === 0 && <p className="empty">Create an owner first to start the PetCare journey.</p>}
    </main>
  </div>;
}

function ContextPicker({ owners, pets, ownerId, petId, setOwner, setPet, lockOwner }: { owners: Owner[]; pets: Pet[]; ownerId: string; petId: string; setOwner: (v: string) => void; setPet: (v: string) => void; lockOwner: boolean }) {
  return <div className="context-picker">{!lockOwner && <label>Viewing<select value={ownerId} onChange={event => { setOwner(event.target.value); const firstPet = pets.find(pet => pet.ownerId === event.target.value); if (firstPet) setPet(firstPet.petId); }}><option value="">All owners</option>{owners.map(owner => <option key={owner.ownerId} value={owner.ownerId}>{owner.ownerName}</option>)}</select></label>}<label>{lockOwner ? 'Your pet' : 'Pet'}<select value={petId} onChange={event => setPet(event.target.value)}><option value="">Choose pet</option>{pets.filter(pet => !ownerId || pet.ownerId === ownerId).map(pet => <option key={pet.petId} value={pet.petId}>{pet.name}</option>)}</select></label></div>;
}

function Overview({ api, owners, pets, selectedOwner, selectedPet, inform }: ViewProps) {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [notifications, setNotifications] = useState<Notification[]>([]); const [nextVaccination, setNextVaccination] = useState<Vaccination | null>(null);
  useEffect(() => { if (!selectedOwner) { setAppointments([]); setNotifications([]); return; } Promise.all([api.appointments(selectedOwner), api.notifications(selectedOwner)]).then(([a, n]) => { setAppointments(a); setNotifications(n); }).catch(error => inform(errorMessage(error))); }, [api, selectedOwner]);
  useEffect(() => { if (!selectedPet) { setNextVaccination(null); return; } api.vaccinations(selectedPet, selectedOwner).then(records => setNextVaccination(records.filter(record => record.nextDueOn).sort((left, right) => String(left.nextDueOn).localeCompare(String(right.nextDueOn)))[0] ?? null)).catch(error => inform(errorMessage(error))); }, [api, selectedPet, selectedOwner]);
  const selectedPets = pets.filter(pet => !selectedOwner || pet.ownerId === selectedOwner);
  return <section className="page-grid owner-overview"><div className="metrics"><Metric label="Number of pets" value={pets.length} icon="🐾" /><Metric label="Upcoming visits" value={appointments.length} icon="◷" /><Metric label="Notifications" value={notifications.length} icon="✦" /></div>
    <Panel title="Next appointment" subtitle="Scheduled through the Appointment service"><Timeline rows={appointments.slice(0, 3).map(item => ({ title: item.reason, meta: dateTime(item.startsAtUtc), tag: appointmentStatus(item.status) }))} empty="No upcoming appointments." /></Panel>
    <Panel title="Care at a glance" subtitle={selectedOwner ? 'Current owner context' : 'Select an owner in the header for live activity'} className="span-2"><div className="pet-cards">{selectedPets.slice(0, 4).map(pet => <article className="pet-card" key={pet.petId}><div className="pet-avatar">{pet.species === 'Cat' || pet.species === 2 ? '🐈' : pet.species === 'Bird' || pet.species === 3 ? '🦜' : '🐕'}</div><div><h4>{pet.name}</h4><p>{String(pet.species)} {pet.breed ? `· ${pet.breed}` : ''}</p><small>{pet.allergies.length ? `Allergies: ${pet.allergies.join(', ')}` : 'No allergies on record'}</small></div></article>)}{!selectedPets.length && <Empty text="No pets in this view yet." />}</div></Panel>
    <Panel title="Vaccination watch" subtitle="Treatment & Notification service"><Timeline rows={nextVaccination ? [{ title: nextVaccination.vaccineName, meta: `Due ${date(nextVaccination.nextDueOn)}`, tag: 'Upcoming' }] : []} empty={selectedPet ? 'No upcoming vaccination is recorded.' : 'Choose a pet to view due care.'} /></Panel>
    <Panel title="Latest notifications" subtitle="Kafka-derived and manually created"><Timeline rows={notifications.slice(0, 4).map(item => ({ title: item.title, meta: dateTime(item.createdAtUtc), tag: notificationStatus(item.status) }))} empty="No notifications for this owner." /></Panel>
  </section>;
}

function VeterinarianOverview({ api, session, inform }: Pick<ViewProps, 'api' | 'session' | 'inform'>) {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [notifications, setNotifications] = useState<Notification[]>([]); const [examinations, setExaminations] = useState<Examination[]>([]); const [appointmentPets, setAppointmentPets] = useState<Pet[]>([]); const [appointmentOwners, setAppointmentOwners] = useState<Owner[]>([]);
  useEffect(() => { Promise.all([api.veterinarianAppointments(session.subject), api.veterinarianNotifications(session.subject), api.veterinarianExaminations(session.subject)]).then(async ([a, n, e]) => { const petIds = [...new Set(a.map(item => item.petId))]; const ownerIds = [...new Set(a.map(item => item.ownerId))]; const [resolvedPets, resolvedOwners] = await Promise.all([Promise.all(petIds.map(id => api.pet(id))), Promise.all(ownerIds.map(id => api.owner(id)))]); setAppointments(a); setNotifications(n); setExaminations(e); setAppointmentPets(resolvedPets); setAppointmentOwners(resolvedOwners); }).catch(error => inform(errorMessage(error))); }, [api, session.subject]);
  return <section className="page-grid"><div className="metrics"><Metric label="Your upcoming visits" value={appointments.length} icon="◷" /><Metric label="Schedule updates" value={notifications.length} icon="✦" /><Metric label="Examinations recorded" value={examinations.length} icon="✚" /></div>
    <Panel title="Your clinic schedule" subtitle="Appointments assigned to your Keycloak-linked veterinarian profile" className="span-2"><Timeline rows={appointments.slice(0, 5).map(item => ({ title: item.reason, meta: dateTime(item.startsAtUtc), detail: <>Pet: {appointmentPets.find(pet => pet.petId === item.petId)?.name ?? 'Unknown pet'}<br />Owner: {appointmentOwners.find(owner => owner.ownerId === item.ownerId)?.ownerName ?? 'Unknown owner'}</>, tag: appointmentStatus(item.status) }))} empty="No upcoming appointments are assigned to you." /></Panel>
    <Panel title="Schedule activity" subtitle="Filled, moved, and cancelled availability slots"><Timeline rows={notifications.slice(0, 4).map(item => ({ title: item.title, meta: dateTime(item.createdAtUtc), detail: item.message, tag: notificationStatus(item.status) }))} empty="No appointment activity has been delivered yet." /></Panel>
  </section>;
}

function ProfilePage({ api, session, owners, refreshDirectory, inform }: Pick<ViewProps, 'api' | 'session' | 'owners' | 'refreshDirectory' | 'inform'>) {
  const ownerOnly = role(session, 'owner') && !role(session, 'admin');
  const veterinarianOnly = role(session, 'veterinarian') && !role(session, 'admin');
  const owner = owners.find(item => item.ownerId === session.subject);
  const [editingOwner, setEditingOwner] = useState<Owner | null>(null);
  const [profile, setProfile] = useState<Veterinarian | null>(null);
  const [form, setForm] = useState({ fullName: '', specialization: '' });
  useEffect(() => { if (!veterinarianOnly) return; api.veterinarian(session.subject).then(item => { setProfile(item); setForm({ fullName: item.fullName, specialization: item.specialization }); }).catch(error => inform(errorMessage(error))); }, [api, session.subject, veterinarianOnly]);
  const saveOwner = async (body: unknown) => { if (!owner) return; try { await api.updateOwner(owner.ownerId, body); await refreshDirectory(); setEditingOwner(null); inform('Profile updated.'); } catch (error) { inform(errorMessage(error)); } };
  return <section className="two-column">
    {ownerOnly && <Panel title="Your profile" subtitle="Personal and contact information" action={owner ? <button className="primary small" onClick={() => setEditingOwner(owner)}>Edit profile</button> : undefined}>{owner ? <div className="profile-details"><div><small>Full name</small><b>{owner.ownerName}</b></div><div><small>Email</small><b>{owner.email}</b></div><div><small>Phone</small><b>{owner.phone}</b></div><div><small>Address</small><b>{owner.address || 'Not provided'}</b></div></div> : <Empty text="No PetOwner profile is linked to this account." />}</Panel>}
    {veterinarianOnly && <Panel title="Clinician profile" subtitle="This name and specialty appear in appointment availability"><form onSubmit={async event => { event.preventDefault(); try { const saved = await api.updateVeterinarian(session.subject, form); setProfile(saved); setForm({ fullName: saved.fullName, specialization: saved.specialization }); inform('Professional profile updated.'); } catch (error) { inform(errorMessage(error)); } }}><Fields><Input label="Professional name" value={form.fullName} onChange={value => setForm({ ...form, fullName: value })} required /><Input label="Specialization" value={form.specialization} onChange={value => setForm({ ...form, specialization: value })} required /></Fields><Actions onClose={() => profile && setForm({ fullName: profile.fullName, specialization: profile.specialization })} submit="Save profile" /></form></Panel>}
    <Panel title="Account settings" subtitle="Password and sign-in preferences"><p className="muted">Security settings are managed by the identity provider.</p><button className="primary" onClick={() => window.location.assign(accountSettingsUrl())}>Manage account settings</button></Panel>
    {editingOwner && <OwnerEditor owner={editingOwner} onClose={() => setEditingOwner(null)} onSave={body => void saveOwner(body)} />}
  </section>;
}

type ViewProps = { api: PetCareApi; session: Session; owners: Owner[]; pets: Pet[]; selectedOwner: string; setSelectedOwner: (v: string) => void; selectedPet: string; setSelectedPet: (v: string) => void; refreshDirectory: () => Promise<void>; inform: (v: string | null) => void };

function Directory({ api, session, owners, pets, selectedOwner, selectedPet, setSelectedOwner, setSelectedPet, refreshDirectory, inform }: ViewProps) {
  const [ownerForm, setOwnerForm] = useState<Owner | null>(null);
  const [petForm, setPetForm] = useState<Pet | null>(null);
  const [vetForm, setVetForm] = useState<Veterinarian | 'new' | null>(null);
  const [vets, setVets] = useState<Veterinarian[]>([]);
  const [clinics, setClinics] = useState<Clinic[]>([]);
  const canManageOwners = role(session, 'admin');
  const canManagePets = role(session, 'owner', 'admin');
  const refreshVeterinarians = async () => { if (!canManageOwners) return; const [nextVets, nextClinics] = await Promise.all([api.vets(), api.clinics()]); setVets(nextVets); setClinics(nextClinics); };
  useEffect(() => { refreshVeterinarians().catch(error => inform(errorMessage(error))); }, [api, canManageOwners]);
  const mutate = async (action: () => Promise<unknown>, message: string) => { try { await action(); await refreshDirectory(); setOwnerForm(null); setPetForm(null); inform(message); } catch (error) { inform(errorMessage(error)); } };
  const saveVeterinarian = async (body: unknown) => { try { if (vetForm === 'new') await api.createVeterinarian(body); else if (vetForm) await api.updateVeterinarian(vetForm.veterinarianId, body); await refreshVeterinarians(); setVetForm(null); inform(vetForm === 'new' ? 'Veterinarian account and profile created.' : 'Veterinarian profile updated.'); } catch (error) { inform(errorMessage(error)); } };
  const deleteVeterinarian = async () => { if (!vetForm || vetForm === 'new') return; try { await api.deleteVeterinarian(vetForm.veterinarianId); await refreshVeterinarians(); setVetForm(null); inform('Veterinarian account and profile deleted.'); } catch (error) { inform(errorMessage(error)); } };
  const selected = pets.find(pet => pet.petId === selectedPet);
  const species = selected ? (typeof selected.species === 'number' ? Object.entries(petSpecies).find(([, id]) => id === selected.species)?.[0] ?? 'Other' : selected.species) : '';
  const visiblePets = pets.filter(pet => !selectedOwner || pet.ownerId === selectedOwner);
  return <section className="two-column">
    {canManageOwners && <Panel title="Owners" subtitle={`${owners.length} profile${owners.length === 1 ? '' : 's'} in Pet Service`} action={<button className="primary small" onClick={() => setOwnerForm({ ownerId: '', ownerName: '', email: '', phone: '', address: '' })}>Add owner</button>}><div className="data-list">{owners.map(owner => <button className={selectedOwner === owner.ownerId ? 'list-row selected' : 'list-row'} key={owner.ownerId} onClick={() => setSelectedOwner(owner.ownerId)}><span className="initials">{owner.ownerName.split(' ').map(word => word[0]).join('').slice(0, 2)}</span><span><b>{owner.ownerName}</b><small>{owner.email} · {owner.phone}</small></span><i onClick={event => { event.stopPropagation(); setOwnerForm(owner); }}>✎</i></button>)}{!owners.length && <Empty text="No owner profiles are available." />}</div></Panel>}
    <Panel title={canManageOwners ? 'Pets' : 'My pets'} subtitle={`${visiblePets.length} companion${visiblePets.length === 1 ? '' : 's'}`} action={canManagePets && owners.length ? <button className="primary small" onClick={() => setPetForm({ petId: '', ownerId: selectedOwner || owners[0].ownerId, name: '', species: 1, breed: '', birthDate: '2022-01-01', weight: 1, microchipNumber: '', allergies: [], chronicConditions: [] })}>Add pet</button> : undefined}><div className="data-list">{visiblePets.map(pet => <button className={selectedPet === pet.petId ? 'list-row selected' : 'list-row'} key={pet.petId} onClick={() => setSelectedPet(pet.petId)}><span className="pet-avatar small-avatar">{pet.species === 'Cat' || pet.species === 2 ? '🐈' : '🐕'}</span><span><b>{pet.name}</b><small>{String(pet.species)}{pet.breed ? ` · ${pet.breed}` : ''} · {pet.weight} kg</small></span>{canManagePets && <i onClick={event => { event.stopPropagation(); setPetForm(pet); }}>✎</i>}</button>)}{!visiblePets.length && <Empty text="Add a pet to start their care record." />}</div></Panel>
    {canManageOwners && <Panel title="Veterinarians" subtitle={`${vets.length} clinician${vets.length === 1 ? '' : 's'} in Appointment Service`} action={<button className="primary small" disabled={!clinics.length} onClick={() => setVetForm('new')}>Add veterinarian</button>}><div className="data-list">{vets.map(vet => <button className="list-row" key={vet.veterinarianId} onClick={() => setVetForm(vet)}><span className="initials">{vet.fullName.split(' ').map(word => word[0]).join('').slice(0, 2)}</span><span><b>{vet.fullName}</b><small>{vet.specialization} · {clinics.find(clinic => clinic.clinicId === vet.clinicId)?.name ?? 'Unknown clinic'}</small></span><i>✎</i></button>)}{!vets.length && <Empty text="No veterinarian profiles are available." />}</div></Panel>}
    {!canManageOwners && <Panel title={selected ? `${selected.name}'s details` : 'Pet details'} subtitle="Health and identification profile">{selected ? <div className="profile-details"><div><small>Species</small><b>{species}</b></div><div><small>Breed</small><b>{selected.breed || 'Not provided'}</b></div><div><small>Birth date</small><b>{date(selected.birthDate)}</b></div><div><small>Weight</small><b>{selected.weight} kg</b></div><div><small>Microchip</small><b>{selected.microchipNumber || 'Not registered'}</b></div><div><small>Allergies</small><b>{selected.allergies.length ? selected.allergies.join(', ') : 'None recorded'}</b></div><div><small>Chronic conditions</small><b>{selected.chronicConditions.length ? selected.chronicConditions.join(', ') : 'None recorded'}</b></div></div> : <Empty text="Select a pet to view its details." />}</Panel>}
    {ownerForm && <OwnerEditor owner={ownerForm} onClose={() => setOwnerForm(null)} onSave={body => mutate(() => ownerForm.ownerId ? api.updateOwner(ownerForm.ownerId, body) : api.createOwner(body), 'Owner saved.')} onDelete={ownerForm.ownerId && canManageOwners ? () => mutate(() => api.deleteOwner(ownerForm.ownerId), 'Owner and associated pets deleted.') : undefined} />}
    {petForm && <PetEditor pet={petForm} owners={owners} onClose={() => setPetForm(null)} onSave={body => mutate(() => petForm.petId ? api.updatePet(petForm.petId, body) : api.createPet(body), 'Pet profile saved.')} onDelete={petForm.petId ? () => mutate(() => api.deletePet(petForm.petId), 'Pet profile deleted.') : undefined} />}
    {vetForm && <VeterinarianEditor veterinarian={vetForm === 'new' ? undefined : vetForm} clinics={clinics} onClose={() => setVetForm(null)} onSave={body => void saveVeterinarian(body)} onDelete={vetForm === 'new' ? undefined : () => void deleteVeterinarian()} />}
  </section>;
}

function OwnerEditor({ owner, onSave, onDelete, onClose }: { owner: Owner; onSave: (body: unknown) => void; onDelete?: () => void; onClose: () => void }) { const [form, setForm] = useState(owner); return <Modal title={owner.ownerId ? 'Edit owner' : 'New owner'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ ownerName: form.ownerName, email: form.email, phone: form.phone, address: form.address || null }); }}><Fields><Input label="Full name" value={form.ownerName} onChange={value => setForm({ ...form, ownerName: value })} required /><Input label="Email" type="email" value={form.email} onChange={value => setForm({ ...form, email: value })} required /><Input label="Phone" value={form.phone} onChange={value => setForm({ ...form, phone: value })} required /><Input label="Address" value={form.address ?? ''} onChange={value => setForm({ ...form, address: value })} /></Fields><Actions onClose={onClose} onDelete={onDelete} /></form></Modal>; }

function PetEditor({ pet, owners, onSave, onDelete, onClose }: { pet: Pet; owners: Owner[]; onSave: (body: unknown) => void; onDelete?: () => void; onClose: () => void }) { const [form, setForm] = useState(pet); const speciesValue = typeof form.species === 'number' ? form.species : petSpecies[form.species] ?? 99; return <Modal title={pet.petId ? `Edit ${pet.name}` : 'New pet'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); const species = Object.entries(petSpecies).find(([, id]) => id === speciesValue)?.[0] ?? 'Other'; const body = { ownerId: form.ownerId, name: form.name.trim(), species, breed: form.breed?.trim() || null, birthDate: form.birthDate, weight: Number(form.weight), microchipNumber: form.microchipNumber?.replaceAll(/[^A-Za-z0-9]/g, '').toUpperCase() || null, allergies: form.allergies, chronicConditions: form.chronicConditions }; if (pet.petId) delete (body as { ownerId?: string }).ownerId; onSave(body); }}><Fields><Select label="Owner" value={form.ownerId} onChange={value => setForm({ ...form, ownerId: value })} options={owners.map(owner => [owner.ownerId, owner.ownerName])} /><Input label="Name" value={form.name} onChange={value => setForm({ ...form, name: value })} required /><Select label="Species" value={String(speciesValue)} onChange={value => setForm({ ...form, species: Number(value) })} options={Object.entries(petSpecies).map(([name, id]) => [String(id), name])} /><Input label="Breed" value={form.breed ?? ''} onChange={value => setForm({ ...form, breed: value })} /><Input label="Birth date" type="date" value={form.birthDate} onChange={value => setForm({ ...form, birthDate: value })} required /><Input label="Weight (kg)" type="number" value={String(form.weight)} onChange={value => setForm({ ...form, weight: Number(value) })} required /><Input label="Microchip (8–30 letters or digits)" value={form.microchipNumber ?? ''} onChange={value => setForm({ ...form, microchipNumber: value })} /><Input label="Allergies (comma separated)" value={form.allergies.join(', ')} onChange={value => setForm({ ...form, allergies: list(value) })} /><Input label="Chronic conditions (comma separated)" value={form.chronicConditions.join(', ')} onChange={value => setForm({ ...form, chronicConditions: list(value) })} /></Fields><Actions onClose={onClose} onDelete={onDelete} /></form></Modal>; }

function VeterinarianEditor({ veterinarian, clinics, onClose, onSave, onDelete }: { veterinarian?: Veterinarian; clinics: Clinic[]; onClose: () => void; onSave: (body: unknown) => void; onDelete?: () => void }) {
  const [form, setForm] = useState({ username: '', temporaryPassword: '', fullName: veterinarian?.fullName ?? '', specialization: veterinarian?.specialization ?? '', licenseNumber: veterinarian?.licenseNumber ?? '', clinicId: veterinarian?.clinicId ?? clinics[0]?.clinicId ?? '' });
  return <Modal title={veterinarian ? `Edit ${veterinarian.fullName}` : 'Add veterinarian'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave(veterinarian ? { fullName: form.fullName, specialization: form.specialization, licenseNumber: form.licenseNumber, clinicId: form.clinicId } : form); }}><Fields>{!veterinarian && <Input label="Username" value={form.username} onChange={value => setForm({ ...form, username: value })} required />}{!veterinarian && <Input label="Temporary password" type="password" value={form.temporaryPassword} onChange={value => setForm({ ...form, temporaryPassword: value })} required />}<Input label="Full name" value={form.fullName} onChange={value => setForm({ ...form, fullName: value })} required /><Input label="Specialization" value={form.specialization} onChange={value => setForm({ ...form, specialization: value })} required /><Input label="License number" value={form.licenseNumber} onChange={value => setForm({ ...form, licenseNumber: value })} required /><Select label="Clinic" value={form.clinicId} onChange={value => setForm({ ...form, clinicId: value })} options={clinics.map(clinic => [clinic.clinicId, `${clinic.name} · ${clinic.location}`])} /></Fields>{!veterinarian && <p className="hint">The veterinarian signs in with this username and changes the temporary password on first login.</p>}{veterinarian && <p className="hint">Veterinarians with appointment history cannot be deleted because their clinical records must remain valid.</p>}<Actions onClose={onClose} onDelete={onDelete} submit={veterinarian ? 'Save veterinarian' : 'Create veterinarian'} /></form></Modal>;
}

function AppointmentsPage({ api, session, owners, pets, selectedOwner, selectedPet, inform }: ViewProps) {
  const [slots, setSlots] = useState<Slot[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]); const [vets, setVets] = useState<Veterinarian[]>([]); const [clinics, setClinics] = useState<Clinic[]>([]); const [booking, setBooking] = useState(false); const [bookingSlotId, setBookingSlotId] = useState<string | null>(null); const [slotEditor, setSlotEditor] = useState(false); const [editingSlot, setEditingSlot] = useState<Slot | null>(null); const [dateFilter, setDateFilter] = useState('');
  const veterinarianOnly = role(session, 'veterinarian') && !role(session, 'admin');
  const refresh = () => Promise.all([api.slots(veterinarianOnly ? session.subject : undefined), api.vets(), api.clinics(), veterinarianOnly ? api.veterinarianAppointments(session.subject) : selectedOwner ? api.appointments(selectedOwner) : Promise.resolve([])]).then(([s, v, c, a]) => { setSlots(s); setVets(v); setClinics(c); setAppointments(a); }).catch(error => inform(errorMessage(error)));
  useEffect(() => { void refresh(); }, [api, selectedOwner]);
  const canManage = role(session, 'owner', 'admin');
  const roleScopedSlots = veterinarianOnly ? slots.filter(slot => slot.veterinarianId === session.subject) : slots;
  const visibleSlots = dateFilter ? roleScopedSlots.filter(slot => slot.startsAtUtc.slice(0, 10) === dateFilter) : roleScopedSlots;
  const slotVets = role(session, 'veterinarian') && !role(session, 'admin') ? vets.filter(vet => vet.veterinarianId === session.subject) : vets;
  const appointmentRows = appointments.map(item => {
    const veterinarian = vets.find(vet => vet.veterinarianId === item.veterinarianId);
    const clinic = clinics.find(entry => entry.clinicId === item.clinicId);
    const doctor = veterinarian?.fullName ?? 'Doctor information unavailable';
    const specialization = veterinarian?.specialization ?? 'Specialization unavailable';
    const place = clinic?.name ?? 'Clinic information unavailable';
    const address = clinic ? `${clinic.location}${clinic.address ? ` — ${clinic.address}` : ''}` : 'Address unavailable';
    return { title: item.reason, meta: dateTime(item.startsAtUtc), detail: <><span>Doctor: {doctor}</span><br /><span>{specialization}</span><br /><span>Place: {place}</span><br /><span>{address}</span></>, tag: appointmentStatus(item.status), actions: canManage ? <AppointmentActions appointment={item} slots={slots} api={api} onChange={refresh} inform={inform} /> : undefined };
  });
  return <section className="page-grid"><Panel title={veterinarianOnly ? 'Your open availability' : 'Open appointment slots'} subtitle={veterinarianOnly ? 'Only availability created for your clinician profile' : 'Live availability from the scheduling service'} className="span-2" action={<label className="filter">Date <input type="date" value={dateFilter} onChange={event => setDateFilter(event.target.value)} /></label>}><div className="slot-grid">{visibleSlots.map(slot => <article key={slot.availabilitySlotId} className="slot"><div><b>{dateTime(slot.startsAtUtc)}</b><p>{slot.veterinarianName} · {slot.specialization}</p><small>{slot.clinicName}</small></div>{canManage && <button className="secondary small" onClick={() => { setBookingSlotId(slot.availabilitySlotId); setBooking(true); }}>Book</button>}{role(session, 'veterinarian', 'admin') && <span className="inline-actions"><button onClick={() => setEditingSlot(slot)}>Edit</button><button onClick={async () => { if (!window.confirm('Remove this open availability slot?')) return; try { await api.deleteSlot(slot.availabilitySlotId); await refresh(); inform('Availability slot removed.'); } catch (error) { inform(errorMessage(error)); } }}>Remove</button></span>}</article>)}{!visibleSlots.length && <Empty text={dateFilter ? 'No open slots on this date.' : veterinarianOnly ? 'You have no open availability yet.' : 'No open slots are currently available.'} />}</div></Panel>
    <Panel title={veterinarianOnly ? 'Your clinic schedule' : 'Your upcoming visits'} subtitle={veterinarianOnly ? 'Appointments assigned to your veterinarian profile.' : selectedOwner ? 'Filter follows the owner selected above.' : 'Select an owner to load appointments.'}><Timeline rows={appointmentRows} empty="No appointments to show." /></Panel>
    <Panel title="Service controls" subtitle="Appointment management"><div className="service-actions">{canManage && <button className="primary" disabled={!selectedOwner || !selectedPet || !visibleSlots.length} onClick={() => { setBookingSlotId(null); setBooking(true); }}>Schedule appointment</button>}{role(session, 'veterinarian', 'admin') && <button className="secondary" disabled={!slotVets.length} onClick={() => setSlotEditor(true)}>Open my availability</button>}</div><p className="hint">Owners can book their pets into open slots. Clinicians can create, update, or remove their own open availability.</p></Panel>
    {booking && <BookingEditor slots={visibleSlots} initialSlotId={bookingSlotId} ownerId={selectedOwner} petId={selectedPet} pets={pets} onClose={() => { setBooking(false); setBookingSlotId(null); }} onSave={async body => { try { await api.bookAppointment(body); setBooking(false); setBookingSlotId(null); await refresh(); inform('Appointment scheduled; the notification worker will process its event.'); } catch (error) { inform(errorMessage(error)); } }} />}
    {(slotEditor || editingSlot) && <SlotEditor vets={slotVets} slot={editingSlot ?? undefined} onClose={() => { setSlotEditor(false); setEditingSlot(null); }} onSave={async body => { try { if (editingSlot) await api.updateSlot(editingSlot.availabilitySlotId, body); else await api.createSlot(body); setSlotEditor(false); setEditingSlot(null); await refresh(); inform(editingSlot ? 'Availability slot updated.' : 'Availability slot created.'); } catch (error) { inform(errorMessage(error)); } }} />}
  </section>;
}

function AppointmentActions({ appointment, slots, api, onChange, inform }: { appointment: Appointment; slots: Slot[]; api: PetCareApi; onChange: () => Promise<void>; inform: (text: string) => void }) { const [reschedule, setReschedule] = useState(false); return <span className="inline-actions">{reschedule ? <select defaultValue="" onChange={async event => { if (!event.target.value) return; try { await api.rescheduleAppointment(appointment.appointmentId, event.target.value); await onChange(); inform('Appointment rescheduled.'); } catch (error) { inform(errorMessage(error)); } }}><option value="">New slot…</option>{slots.map(slot => <option key={slot.availabilitySlotId} value={slot.availabilitySlotId}>{dateTime(slot.startsAtUtc)} · {slot.veterinarianName}</option>)}</select> : <button onClick={() => setReschedule(true)}>Move</button>}<button onClick={async () => { const reason = window.prompt('Cancellation reason (optional):') ?? undefined; try { await api.cancelAppointment(appointment.appointmentId, reason); await onChange(); inform('Appointment cancelled and its slot reopened.'); } catch (error) { inform(errorMessage(error)); } }}>Cancel</button></span>; }

function BookingEditor({ slots, initialSlotId, ownerId, petId, pets, onClose, onSave }: { slots: Slot[]; initialSlotId: string | null; ownerId: string; petId: string; pets: Pet[]; onClose: () => void; onSave: (body: unknown) => void }) { const selectedSlotId = initialSlotId && slots.some(slot => slot.availabilitySlotId === initialSlotId) ? initialSlotId : slots[0]?.availabilitySlotId ?? ''; const [form, setForm] = useState({ ownerId, petId, availabilitySlotId: selectedSlotId, reason: '' }); return <Modal title="Schedule appointment" onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave(form); }}><Fields><Select label="Pet" value={form.petId} onChange={value => { const pet = pets.find(item => item.petId === value); setForm({ ...form, petId: value, ownerId: pet?.ownerId ?? form.ownerId }); }} options={pets.filter(pet => !ownerId || pet.ownerId === ownerId).map(pet => [pet.petId, pet.name])} /><Select label="Open slot" value={form.availabilitySlotId} onChange={value => setForm({ ...form, availabilitySlotId: value })} options={slots.map(slot => [slot.availabilitySlotId, `${dateTime(slot.startsAtUtc)} — ${slot.veterinarianName}`])} /><Input label="Reason for visit" value={form.reason} onChange={value => setForm({ ...form, reason: value })} required /></Fields><Actions onClose={onClose} submit="Book appointment" /></form></Modal>; }

function SlotEditor({ vets, slot, onClose, onSave }: { vets: Veterinarian[]; slot?: Slot; onClose: () => void; onSave: (body: unknown) => void }) { const [form, setForm] = useState({ veterinarianId: slot?.veterinarianId ?? vets[0]?.veterinarianId ?? '', startsAtUtc: slot ? inputDateTime(new Date(slot.startsAtUtc)) : inputDateTime(), endsAtUtc: slot ? inputDateTime(new Date(slot.endsAtUtc)) : inputDateTime(new Date(Date.now() + 30 * 60_000)) }); return <Modal title={slot ? 'Edit availability slot' : 'Open availability slot'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ ...form, startsAtUtc: new Date(form.startsAtUtc).toISOString(), endsAtUtc: new Date(form.endsAtUtc).toISOString() }); }}><Fields><Select label="Veterinarian" value={form.veterinarianId} onChange={value => setForm({ ...form, veterinarianId: value })} options={vets.map(vet => [vet.veterinarianId, `${vet.fullName} · ${vet.specialization}`])} /><Input label="Starts" type="datetime-local" value={form.startsAtUtc} onChange={value => setForm({ ...form, startsAtUtc: value })} required /><Input label="Ends" type="datetime-local" value={form.endsAtUtc} onChange={value => setForm({ ...form, endsAtUtc: value })} required /></Fields><Actions onClose={onClose} submit={slot ? 'Save availability' : 'Create slot'} /></form></Modal>; }

function CarePage({ api, session, pets, selectedPet, selectedOwner, inform }: ViewProps) {
  const [examinations, setExaminations] = useState<Examination[]>([]); const [vaccinations, setVaccinations] = useState<Vaccination[]>([]); const [vets, setVets] = useState<Veterinarian[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]); const [selectedAppointment, setSelectedAppointment] = useState(''); const [examForm, setExamForm] = useState(false); const [vaccinationForm, setVaccinationForm] = useState(false); const [editingExam, setEditingExam] = useState<Examination | null>(null); const [editingVaccination, setEditingVaccination] = useState<Vaccination | null>(null);
  const selected = pets.find(pet => pet.petId === selectedPet); const clinician = role(session, 'veterinarian', 'admin'); const veterinarianOnly = role(session, 'veterinarian') && !role(session, 'admin');
  const refresh = () => { if (veterinarianOnly) return Promise.all([api.veterinarianExaminations(session.subject), api.veterinarianVaccinations(session.subject), api.veterinarianClinicalAppointments(session.subject)]).then(([e, v, a]) => { setExaminations(e); setVaccinations(v); setAppointments(a); setSelectedAppointment(current => a.some(item => item.appointmentId === current) ? current : a[0]?.appointmentId ?? ''); }).catch(error => inform(errorMessage(error))); if (!selectedPet) return Promise.resolve(); return Promise.all([api.examinations(selectedPet, selectedOwner), api.vaccinations(selectedPet, selectedOwner), api.vets()]).then(([e, v, nextVets]) => { setExaminations(e); setVaccinations(v); setVets(nextVets); }).catch(error => inform(errorMessage(error))); };
  useEffect(() => { void refresh(); }, [api, selectedPet, veterinarianOnly]);
  const appointment = appointments.find(item => item.appointmentId === selectedAppointment); const appointmentPet = appointment ? { petId: appointment.petId, ownerId: appointment.ownerId, name: `Scheduled patient ${appointment.petId.slice(0, 8)}`, species: 99, birthDate: '', weight: 0, allergies: [], chronicConditions: [] } as Pet : undefined; const recordPet = veterinarianOnly ? appointmentPet : selected; const recordOwnerId = appointment?.ownerId ?? (selectedOwner || recordPet?.ownerId || ''); const recordingVets = veterinarianOnly ? [{ veterinarianId: session.subject, clinicId: '', fullName: 'Your clinician profile', specialization: '', isAvailable: true }] : vets;
  const canModify = (veterinarianId: string) => role(session, 'admin') || veterinarianId === session.subject;
  const remove = async (action: () => Promise<void>, message: string) => { if (!window.confirm('Remove this clinical record?')) return; try { await action(); await refresh(); inform(message); } catch (error) { inform(errorMessage(error)); } };
  return <section className="two-column">{veterinarianOnly && <Panel title="Appointment patient" subtitle="Select a current or past appointment before recording care" action={<label className="filter">Appointment <select value={selectedAppointment} onChange={event => setSelectedAppointment(event.target.value)}>{appointments.map(item => <option key={item.appointmentId} value={item.appointmentId}>{dateTime(item.startsAtUtc)} · {item.reason}</option>)}</select></label>}><p className="muted">Care entries are connected to the selected appointment and remain visible only in your own clinical history.</p></Panel>}
    <Panel title={veterinarianOnly ? 'Your examination history' : selected ? `${selected.name}'s medical history` : 'Medical history'} subtitle={veterinarianOnly ? 'Examinations you recorded' : 'Treatment records'} action={clinician && recordPet ? <button className="primary small" onClick={() => { setEditingExam(null); setExamForm(true); }}>Record examination</button> : undefined}><Timeline rows={examinations.map(exam => ({ title: exam.diagnosis, meta: `${dateTime(exam.examinedAtUtc)} · ${exam.treatmentPlan}`, detail: `${veterinarianOnly ? `Patient reference: ${exam.petId.slice(0, 8)}. ` : ''}${exam.medications.length ? `Medications: ${exam.medications.join(', ')}. ` : ''}${exam.notes ?? ''}`, tag: exam.nextControlAtUtc ? `Follow-up ${dateTime(exam.nextControlAtUtc)}` : undefined, actions: clinician && canModify(exam.veterinarianId) ? <span className="inline-actions"><button onClick={() => { setEditingExam(exam); setExamForm(true); }}>Edit</button><button onClick={() => void remove(() => api.deleteExamination(exam.id), 'Examination removed.')}>Remove</button></span> : undefined }))} empty={veterinarianOnly ? 'You have not recorded any examinations yet.' : selected ? 'No examinations have been recorded.' : 'Choose a pet to view its history.'} /></Panel>
    <Panel title={veterinarianOnly ? 'Your vaccination history' : 'Vaccination record'} subtitle={veterinarianOnly ? 'Vaccinations you recorded' : 'Due-date reminders are generated automatically'} action={clinician && recordPet ? <button className="primary small" onClick={() => { setEditingVaccination(null); setVaccinationForm(true); }}>Record vaccination</button> : undefined}><Timeline rows={vaccinations.map(vaccination => ({ title: vaccination.vaccineName, meta: `Administered ${date(vaccination.administeredOn)}`, detail: `${veterinarianOnly ? `Patient reference: ${vaccination.petId.slice(0, 8)}. ` : ''}${vaccination.nextDueOn ? `Next due ${date(vaccination.nextDueOn)}` : 'No next due date set'}`, tag: vaccination.batchNumber ?? undefined, actions: clinician && canModify(vaccination.veterinarianId) ? <span className="inline-actions"><button onClick={() => { setEditingVaccination(vaccination); setVaccinationForm(true); }}>Edit</button><button onClick={() => void remove(() => api.deleteVaccination(vaccination.id), 'Vaccination removed.')}>Remove</button></span> : undefined }))} empty={veterinarianOnly ? 'You have not recorded any vaccinations yet.' : selected ? 'No vaccinations have been recorded.' : 'Choose a pet to view vaccinations.'} /></Panel>
    {examForm && recordPet && <ExaminationEditor pet={recordPet} ownerId={recordOwnerId} appointmentId={appointment?.appointmentId} record={editingExam ?? undefined} vets={recordingVets} onClose={() => { setExamForm(false); setEditingExam(null); }} onSave={async body => { try { if (editingExam) await api.updateExamination(editingExam.id, body); else await api.createExamination(body); setExamForm(false); setEditingExam(null); await refresh(); inform(editingExam ? 'Examination updated.' : 'Medical examination recorded.'); } catch (error) { inform(errorMessage(error)); } }} />}
    {vaccinationForm && recordPet && <VaccinationEditor pet={recordPet} ownerId={recordOwnerId} record={editingVaccination ?? undefined} vets={recordingVets} onClose={() => { setVaccinationForm(false); setEditingVaccination(null); }} onSave={async body => { try { if (editingVaccination) await api.updateVaccination(editingVaccination.id, body); else await api.createVaccination(body); setVaccinationForm(false); setEditingVaccination(null); await refresh(); inform(editingVaccination ? 'Vaccination updated.' : 'Vaccination recorded.'); } catch (error) { inform(errorMessage(error)); } }} />}
  </section>;
}

function ExaminationEditor({ pet, ownerId, appointmentId, record, vets, onClose, onSave }: { pet: Pet; ownerId: string; appointmentId?: string; record?: Examination; vets: Veterinarian[]; onClose: () => void; onSave: (body: unknown) => void }) { const [form, setForm] = useState({ diagnosis: record?.diagnosis ?? '', treatmentPlan: record?.treatmentPlan ?? '', medications: record?.medications.join(', ') ?? '', examinedAtUtc: record ? inputDateTime(new Date(record.examinedAtUtc)) : inputDateTime(), nextControlAtUtc: record?.nextControlAtUtc ? inputDateTime(new Date(record.nextControlAtUtc)) : '', notes: record?.notes ?? '', veterinarianId: record?.veterinarianId ?? vets[0]?.veterinarianId ?? '' }); return <Modal title={`${record ? 'Edit' : 'Record'} examination · ${pet.name}`} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ petId: pet.petId, ownerId, veterinarianId: form.veterinarianId, appointmentId: appointmentId ?? record?.appointmentId ?? null, examinedAtUtc: new Date(form.examinedAtUtc).toISOString(), diagnosis: form.diagnosis, treatmentPlan: form.treatmentPlan, medications: list(form.medications), nextControlAtUtc: form.nextControlAtUtc ? new Date(form.nextControlAtUtc).toISOString() : null, notes: form.notes || null }); }}><Fields><Select label="Veterinarian" value={form.veterinarianId} onChange={value => setForm({ ...form, veterinarianId: value })} options={vets.map(vet => [vet.veterinarianId, `${vet.fullName} ${vet.specialization ? `· ${vet.specialization}` : ''}`])} /><Input label="Examined at" type="datetime-local" value={form.examinedAtUtc} onChange={value => setForm({ ...form, examinedAtUtc: value })} required /><Input label="Diagnosis" value={form.diagnosis} onChange={value => setForm({ ...form, diagnosis: value })} required /><Input label="Treatment plan" value={form.treatmentPlan} onChange={value => setForm({ ...form, treatmentPlan: value })} required /><Input label="Medications (comma separated)" value={form.medications} onChange={value => setForm({ ...form, medications: value })} /><Input label="Next control" type="datetime-local" value={form.nextControlAtUtc} onChange={value => setForm({ ...form, nextControlAtUtc: value })} /><Input label="Clinical notes" value={form.notes} onChange={value => setForm({ ...form, notes: value })} /></Fields><Actions onClose={onClose} submit={record ? 'Save examination' : 'Record examination'} /></form></Modal>; }

function VaccinationEditor({ pet, ownerId, record, vets, onClose, onSave }: { pet: Pet; ownerId: string; record?: Vaccination; vets: Veterinarian[]; onClose: () => void; onSave: (body: unknown) => void }) { const [form, setForm] = useState({ veterinarianId: record?.veterinarianId ?? vets[0]?.veterinarianId ?? '', vaccineName: record?.vaccineName ?? '', administeredOn: record?.administeredOn ?? today(), nextDueOn: record?.nextDueOn ?? '', batchNumber: record?.batchNumber ?? '' }); return <Modal title={`${record ? 'Edit' : 'Record'} vaccination · ${pet.name}`} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ petId: pet.petId, ownerId, veterinarianId: form.veterinarianId, vaccineName: form.vaccineName, administeredOn: form.administeredOn, nextDueOn: form.nextDueOn || null, batchNumber: form.batchNumber || null }); }}><Fields><Select label="Veterinarian" value={form.veterinarianId} onChange={value => setForm({ ...form, veterinarianId: value })} options={vets.map(vet => [vet.veterinarianId, `${vet.fullName} ${vet.specialization ? `· ${vet.specialization}` : ''}`])} /><Input label="Vaccine" value={form.vaccineName} onChange={value => setForm({ ...form, vaccineName: value })} required /><Input label="Administered on" type="date" value={form.administeredOn} onChange={value => setForm({ ...form, administeredOn: value })} required /><Input label="Next due on" type="date" value={form.nextDueOn} onChange={value => setForm({ ...form, nextDueOn: value })} /><Input label="Batch number" value={form.batchNumber} onChange={value => setForm({ ...form, batchNumber: value })} /></Fields><Actions onClose={onClose} submit={record ? 'Save vaccination' : 'Record vaccination'} /></form></Modal>; }

function NotificationsPage({ api, session, pets, selectedOwner, selectedPet, inform }: ViewProps) {
  const [notifications, setNotifications] = useState<Notification[]>([]); const [create, setCreate] = useState(false);
  const veterinarianOnly = role(session, 'veterinarian') && !role(session, 'admin');
  const refresh = () => { if (veterinarianOnly) return api.veterinarianNotifications(session.subject).then(setNotifications).catch(error => inform(errorMessage(error))); if (!selectedOwner) return Promise.resolve(); return api.notifications(selectedOwner).then(setNotifications).catch(error => inform(errorMessage(error))); };
  useEffect(() => { void refresh(); }, [api, selectedOwner, veterinarianOnly]);
  return <section className="two-column"><Panel title={veterinarianOnly ? 'Your schedule activity' : 'Notification activity'} subtitle={veterinarianOnly ? 'Appointment events delivered to your veterinarian profile' : selectedOwner ? 'Newest first for the selected owner' : 'Select an owner to read their activity'} action={role(session, 'admin') ? <button className="primary small" disabled={!selectedOwner || !selectedPet} onClick={() => setCreate(true)}>Create notification</button> : undefined}><div className="notification-list">{notifications.map(notification => <article className="notification" key={notification.id}><span className="notification-icon">{String(notification.type).toLowerCase().includes('vacc') ? '✚' : '◉'}</span><div><div className="row-title"><h4>{notification.title}</h4><Badge>{notificationStatus(notification.status)}</Badge></div><p>{notification.message}</p><small>Scheduled {dateTime(notification.scheduledForUtc)} · created {dateTime(notification.createdAtUtc)}</small></div></article>)}{!notifications.length && <Empty text={veterinarianOnly ? 'No appointment activity has been delivered to you yet.' : selectedOwner ? 'There are no notifications for this owner.' : 'Choose an owner to load notifications.'} />}</div></Panel>
    {create && <NotificationEditor ownerId={selectedOwner} petId={selectedPet} pets={pets} onClose={() => setCreate(false)} onSave={async body => { try { await api.createNotification(body); setCreate(false); await refresh(); inform('Notification created.'); } catch (error) { inform(errorMessage(error)); } }} />}
  </section>;
}

function NotificationEditor({ ownerId, petId, pets, onClose, onSave }: { ownerId: string; petId: string; pets: Pet[]; onClose: () => void; onSave: (body: unknown) => void }) { const [form, setForm] = useState<{ petId: string; type: string; title: string; message: string; scheduledForUtc: string; sourceEventId: string }>({ petId, type: 'AppointmentScheduled', title: '', message: '', scheduledForUtc: inputDateTime(), sourceEventId: crypto.randomUUID() }); return <Modal title="Create notification" onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ ownerId, petId: form.petId, type: form.type, title: form.title, message: form.message, scheduledForUtc: new Date(form.scheduledForUtc).toISOString(), sourceEventId: form.sourceEventId }); }}><Fields><Select label="Pet" value={form.petId} onChange={value => setForm({ ...form, petId: value })} options={pets.filter(pet => pet.ownerId === ownerId).map(pet => [pet.petId, pet.name])} /><Select label="Type" value={form.type} onChange={value => setForm({ ...form, type: value })} options={['AppointmentScheduled', 'AppointmentCancelled', 'AppointmentRescheduled', 'VaccinationReminder', 'FollowUpReminder'].map(type => [type, type])} /><Input label="Title" value={form.title} onChange={value => setForm({ ...form, title: value })} required /><Input label="Message" value={form.message} onChange={value => setForm({ ...form, message: value })} required /><Input label="Scheduled for" type="datetime-local" value={form.scheduledForUtc} onChange={value => setForm({ ...form, scheduledForUtc: value })} required /><Input label="Source event ID" value={form.sourceEventId} onChange={value => setForm({ ...form, sourceEventId: value })} required /></Fields><Actions onClose={onClose} submit="Create notification" /></form></Modal>; }

function Panel({ title, subtitle, action, children, className = '' }: { title: string; subtitle?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}><div className="panel-header"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>; }
function Metric({ label, value, icon }: { label: string; value: number; icon: string }) { return <article className="metric"><span>{icon}</span><div><b>{value}</b><p>{label}</p></div></article>; }
function Badge({ children }: { children: ReactNode }) { return <span className="badge">{children}</span>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function Timeline({ rows, empty }: { rows: { title: string; meta: string; detail?: ReactNode; tag?: string; actions?: ReactNode }[]; empty: string }) { return <div className="timeline">{rows.map((row, index) => <article className="timeline-row" key={`${row.title}-${index}`}><span className="timeline-dot"/><div><div className="row-title"><h4>{row.title}</h4>{row.tag && <Badge>{row.tag}</Badge>}</div><p>{row.meta}</p>{row.detail && <small>{row.detail}</small>}{row.actions && <div className="row-actions">{row.actions}</div>}</div></article>)}{!rows.length && <Empty text={empty} />}</div>; }
function Fields({ children }: { children: ReactNode }) { return <div className="fields">{children}</div>; }
function Input({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={event => onChange(event.target.value)} required={required} /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label className="field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)} required><option value="" disabled>Choose…</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={event => event.stopPropagation()}><div className="modal-header"><h3>{title}</h3><button className="icon-button" onClick={onClose}>×</button></div>{children}</div></div>; }
function Actions({ onClose, onDelete, submit = 'Save changes' }: { onClose: () => void; onDelete?: () => void; submit?: string }) { return <div className="form-actions">{onDelete && <button type="button" className="danger" onClick={() => { if (window.confirm('This cannot be undone. Continue?')) onDelete(); }}>Delete</button>}<span/><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">{submit}</button></div>; }

export default App;
